Introduced a work-around for AIX where cpio does not fail immediatelly if not enough space on the output device, rather printing out a bunch of useless messages and going on (keep failing).
git-svn-id: https://svn.code.sf.net/p/tsc-tpm/code@127 af914a7b-af0d-0410-90d3-cea0664cafdb

diff --git a/scripts/tpm-install b/scripts/tpm-install
--- a/scripts/tpm-install
+++ b/scripts/tpm-install
@@ -183,13 +183,23 @@ extract()
 {
   error_codes=`{
     (trace_and_run ${STREAM_UNCOMPRESS_COMMAND} || _echo ${?} 1>&5) | {
-      (trace_and_run cpio -idcv ${EXTRACT_ITEMS} 2>&1 || _echo ${?} 1>&5) | {
+      (trace_and_run cpio -idcvu ${EXTRACT_ITEMS} 2>&1 || _echo ${?} 1>&5) | {
         # The following is needed because cpio option -v on Linux sends
         # its output to stderr. So in case of error we need the data in 
         # the error log file available for reporting.
         #
         while read line; do
-          _echo ${line}; _echo ${line} 1>&2
+          _echo "${line}"; _echo "${line}" 1>&2
+          # The work-around for AIX: when not enough space on output device,
+          # cpio on AIX does not fail immediatelly, rather tries to go on with
+          # an error message that starts with <cpio:> or <cpio :>
+          #
+          case "${line}" in
+            'cpio:'* | 'cpio :'*)
+              echo 3 1>&5
+              break
+            ;;
+          esac
         done | progress Unpacking 1>&3
       }
     }
@@ -198,7 +208,7 @@ extract()
   [ "${error_codes:+set}" = set ] && {
     print_error "ERROR: ${progname}: Unpacking failed."
     [ "${VERBOSE:+set}" = set ] && {
-      cat "${error_log}" | sed 's/^/stderr> /' 1>&2
+      tail -20 "${error_log}" | sed 's/^/stderr> /' 1>&2
     }
     return 4
   }
